Allow to use HA Scripts as Button Entity
unfoldedcircle/integration-home-assistant pull request #20
Opened 2023-09-08 15:27 UTC by splattner

2023-09-11 07:08 UTC, zehnm requested changes
Thank you for your contribution! The script support is working fine 👍 
Please fix the cosmetic formatting issues reported by Clippy, then I will merge this PR.

The only thing we could discuss is to use a switch instead of a button for HA scripts. This would allow to:
- stop a running script (at least according to the HA docs. I don't know if the script will be killed, or if it needs specific support to be stoppable).
- see when a (long running) script is active on the remote.

For me personally it doesn't really matter right now. I still have to migrate everything to HA and I'm not using scripts yet (just a matter of time...).

2023-09-11 07:08 UTC, zehnm commented on src/client/service/mod.rs
> +mod button;
Please fix formatting. See `cargo fmt --all -- --check` output (or GitHub action).

2023-09-11 11:55 UTC, splattner commented on src/client/service/button.rs
> +            &_ => "press"
sure, I just did

2023-09-11 11:55 UTC, splattner commented on src/client/service/mod.rs
> +mod button;
also fixed

2023-09-11 12:02 UTC, splattner commented
> Thank you for your contribution! The script support is working fine 👍 Please fix the cosmetic formatting issues reported by `cargo fmt`, then I will merge this PR. You can ignore the reported issue by Clippy, I've fixed that on the main branch.
> 
> The only thing we could discuss is to use a switch instead of a button for HA scripts. This would allow to:
> 
> * stop a running script (at least according to the HA docs. I don't know if the script will be killed, or if it needs specific support to be stoppable).
> * see when a (long running) script is active on the remote.
> 
> For me personally it doesn't really matter right now. I still have to migrate everything to HA and I'm not using scripts yet (just a matter of time...).

thanks for reviewing it. Fmt errors are fixed, still new to Rust, that was my first code in rust ever ;)

I actually never had the need to stop a running scripts, mine are quite short. So for me, a button is enough. Yes, HA allows to stop a running script, there is a `turn_on` & `turn_off` and also a `toggle` service. And what I did here, is just calling it by name, which is what I did so far in HA.
My personal opinion, I think its confusing to have this as a Switch, therefore I'd rather leave it as a Button. with only the the call by name.

2023-09-11 12:11 UTC, zehnm approved these changes
Thanks again! I'll merge it, button entitiy it is 👍 

You haven't picked the easiest Rust project to start with ;-)
Also some of my "earlier" work and a bit complicated with the Actor stuff.

2023-09-11 12:12 UTC, merged

2023-09-19 11:12 UTC, uvjim commented
A quick question on this one now that it has been released... How do I pass parameters to the script that needs to be called?  I can't seem to find that in the Web Configurator.

2023-09-19 11:59 UTC, zehnm commented
> How do I pass parameters to the script that needs to be called?

That is currently not possible.
For now, HA scripts can only be triggered. Supporting parameters will require more work, most likely with a new entity type, which supports dynamic parameters.

Since this PR is merged, let's continue in #20