Updated HA driver to work with unified integration
unfoldedcircle/integration-home-assistant pull request #58
Opened 2024-07-18 10:38 UTC by albaintor

This updated driver supports :

- Handle of new events to subscribe to in order to be able to receive an updated list of subscribed entities fro
- Handle of updated subscribed entities from the remote's core to the driver then will be notified to new unified integration in order to receive only the necessary events
- Fallback to standard events (all events) in case of no support for these new events
- Handle of subscribed entities from the unified HA component in order to update the subscribed entities to the core

To be tested with the https://github.com/albaintor/hass-unfoldedcircle/tree/unified_intregration

2024-08-02 10:01 UTC, zehnm requested changes
Please fix source code format & linting issues (see failed PR checks):
https://github.com/unfoldedcircle/integration-home-assistant/blob/c1f730cb09d90f76bd0ac70ca45bb5521ac5af72/CONTRIBUTING.md?plain=1#L42-L59

Auto-format source code: `cargo fmt --all` (or if you use IntelliJ, you can enable it as an auto-save action).

Failing compile fix (not an issue of your PR, but the latest stable Rust compiler `rustup update`)) - update time crate:
```
cargo update -p time
```
After the update, `cargo test` will succeed.

2024-08-02 10:06 UTC, zehnm commented
I'll fix the main branch with the `time` crate update and the newly reported clippy issues with the latest Rust version (Clippy is getting "better" with each update), then you can rebase your branch and don't have to fix these things.

2024-08-02 10:09 UTC, albaintor commented
Ok all done

2024-08-08 08:02 UTC, zehnm requested changes
Initial code review only, testing the new logic will be next.

Please fix the expect, cloning & logging issues in the review comments. This should also make the new itertools crate obsolete.

The main branch is updated with linting fixes and dependency updates.

2024-08-08 21:45 UTC, albaintor commented
Hi Markus,

I am away for 2 days I will review and update the PR after then. Thanks

Le 8 août 2024 à 10:03, Markus Zehnder ***@***.***> a écrit :

﻿

@zehnm requested changes on this pull request.

Initial code review only, testing the new logic will be next.

Please fix the expect, cloning & logging issues in the review comments. This should also make the new itertools crate obsolete.

The main branch is updated with linting fixes and dependency updates.

________________________________

In src/controller/handler/ha_connection.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708783788>:

> @@ -141,6 +141,17 @@ impl Handler<ConnectMsg> for Controller {
                         act.ha_client = Some(addr);
                         act.ha_reconnect_duration = act.settings.hass.reconnect.duration;
                         act.ha_reconnect_attempt = 0;
+                        debug!("Sending subscribed entities to client for events subscriptions");
+                        if let Some(session) = act.sessions.values().next() {
+                            let entities = session.subscribed_entities.clone();
+                            if let Some(ha_client) = &act.ha_client {
+                                ha_client
+                                    .try_send(SubscribedEntities {
+                                        entity_ids: entities,
+                                    })
+                                    .expect("Error updating subscribed entities to client")


Using expect will terminate the process on failure.
This should only be used in non-recoverable situations, or if something might "never" happen to indicate a bug.
Here, it's more appropriate to only log an error, since the client sending the ConnectMsg request doesn't wait for the response (using Context.notify()).

________________________________

In src/controller/handler/ha_event.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708828570>:

> +            let mut entity_ids = Vec::with_capacity(msg.entities.len());
+            for entity in msg.entities.clone() {
+                entity_ids.push(entity.entity_id);
+            }
+            debug!(
+                "[{}] {} : {}",
+                ws_id,
+                "Received new available entities to send to remote",
+                itertools::join(entity_ids, ",")
+            );


Cloning all entity objects to only log the ids (if debug level is enabled) is a lot of overhead!
It's enough to just collect the references to the entity ids:

let entity_ids: Vec<&String> = msg.entities.iter().map(|x| &x.entity_id).collect();
debug!("[{ws_id}] Received new available entities to send to remote: {entity_ids:?}");

________________________________

In src/controller/handler/r2_request.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708835057>:

> @@ -120,11 +120,39 @@ impl Handler<R2RequestMsg> for Controller {
         let ha_client = self.ha_client.clone();

         // FIXME quick & dirty request id "mapping". This requires a rewrite with proper callback & timeout handling!
+        let mut entitiy_ids = Default::default();


Typo: entity_ids

________________________________

In src/controller/handler/r2_request.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708842058>:

> +                        debug!(
+                            "[{}] Requesting subscribed entities states from HA {}",
+                            msg.ws_id,
+                            itertools::join(entitiy_ids.clone(), ",")
+                        );


No need to clone the entity id hashset for a debug log.

debug!(
    "[{}] Requesting subscribed entities states from HA: {entitiy_ids:?}",
    msg.ws_id
);

________________________________

In src/controller/handler/r2_request.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708847695>:

> +                    // I'm not aware of a different way to just retrieve the attributes. The get_states
+                    // call returns everything, so we have to filter our response to UCR2.
+
+                    // get states from Home Assistant. Response from HA will call AvailableEntities handler
+                    // or call custom UC HA component command if available
+                    // to get entity states on subscribed entities only
+                    if let Some(ha_client) = ha_client {
+                        debug!(
+                            "[{}] Requesting subscribed entities states from HA {}",
+                            msg.ws_id,
+                            itertools::join(entitiy_ids.clone(), ",")
+                        );
+                        ha_client
+                            .send(GetStates {
+                                remote_id: msg.ws_id,
+                                entity_ids: entitiy_ids.clone(),


No need to clone the entity id hashset: this is the last reference, so the data can be passed on without cloning: entity_ids: entitiy_ids

After the typo is fixed:

GetStates {
  remote_id: msg.ws_id,
  entity_ids,
}

________________________________

In src/client/subscribed_entities.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708861508>:

> +        debug!(
+            "[{}] {} : {}",
+            self.id,
+            "Updated subscribed entities",
+            itertools::join(&msg.entity_ids, ",")
+        );


Put static log texts in format string, no need for itertools:

debug!(
    "[{}] Updated subscribed entities: {:?}",
    self.id, msg.entity_ids
);

________________________________

In src/client/mod.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708870773>:

> +                    debug!(
+                        "[{}] {}",
+                        self.id, "Received request from HA for configuring subscribed entities"
+                    );


When using logging, static strings should be put in the format string and not as a parameter.

________________________________

In src/client/mod.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708871847>:

> +                    debug!(
+                        "[{}] {} ({})",
+                        self.id,
+                        "Received HA response for unfoldedcircle/info custom event",
+                        success
+                    );


When using logging, static strings should be put in the format string and not as a parameter.

________________________________

In src/client/mod.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708873048>:

> +                        debug!(
+                            "[{}] {} : {}",
+                            self.id,
+                            "Initialize subscribed entities",
+                            itertools::join(&self.subscribed_entities, ",")
+                        );


When using logging, static strings should be put in the format string and not as a parameter.
No need for itertools, see other comments.

________________________________

In src/client/mod.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708873435>:

> +                    debug!(
+                        "[{}] {} ({})",
+                        self.id,
+                        "Received HA response for unfoldedcircle/event/configure/subscribe event",
+                        success
+                    );


When using logging, static strings should be put in the format string and not as a parameter.

________________________________

In src/client/mod.rs<https://github.com/unfoldedcircle/integration-home-assistant/pull/58#discussion_r1708873866>:

> +                    debug!(
+                        "[{}] {} ({})",
+                        self.id,
+                        "Received H [...]

2024-08-09 14:36 UTC, albaintor commented on src/controller/handler/ha_connection.rs
> +                                    .expect("Error updating subscribed entities to client")
Ok thanks I am still learning rust. I did this because you cannot chain conditions when there is a take "if Some(...) && condition2", getting an unstable warning... Changed it

2024-08-09 14:38 UTC, albaintor commented on src/controller/handler/ha_event.rs
> +            );
Yes much better :-) !

2024-08-09 14:41 UTC, albaintor commented on src/controller/handler/r2_request.rs
> +                        );
Ok I removed the .clone() from the hashset, but not sure to follow your proposition below. It should be this ?: 
```python
debug!(
                            "[{}] Requesting subscribed entities states from HA {}",
                            msg.ws_id,
                            itertools::join(entitiy_ids, ",")
                        );```

2024-08-09 14:45 UTC, albaintor commented on src/controller/handler/r2_request.rs
> +                                entity_ids: entitiy_ids.clone(),
Done

2024-08-09 14:49 UTC, albaintor commented on src/client/mod.rs
> +                    );
Done

2024-08-09 15:01 UTC, albaintor commented
I also merged the last commits from main branch

2024-08-22 14:59 UTC, zehnm requested changes
Format & linting checks are failing.

Make sure that you have the latest Rust compiler & tools installed:
```shell
rustup update
```

Format code:
```shell
cargo fmt --all
```

Most linting issues can be fixed automatically:
```shell
cargo clippy --fix
```

This leaves some dead code:
```
   --> src/client/mod.rs:566:9
    |
566 |         self.remote_id.is_empty();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
    |
566 |         let _ = self.remote_id.is_empty();
    |         +++++++

```

Original code: `if self.remote_id == "" {}`

2024-08-23 13:05 UTC, zehnm approved these changes
Looks good and it works without issues with a normal HA installation missing the UC component.
Thanks a lot!

I'll merge it and include it in the upcoming 1.9.3 beta firmware release.
Afterwards I'll enhance the integration to use the external token and server URL information, if available.

2024-08-23 13:07 UTC, merged